### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by valentinamacek** [valentinamacek/Gibanje_cen#1]
Poskusila sem pognati aplikacijo v binderju, pa mi ne deluje.

**Comment by valentinamacek** [comment]
Ostal mi je samo še ta problem z binderjem, sicer pa je projekt končan.

Lp, 
Valentina

**Comment by majbc1999** [comment]
Živjo,

se opravičujem za pozen odziv. Torej, na hitro vidim težavo s funkcijo `url`. Vidim, da ji podajaš pot kot parameter (na primer: `redirect(url('/'))`). Namesto tega, ji moraš kot argument podati ime funkcije iz `app.py`, torej za prejšnji primer `redirect(url('index'))`. To moraš popraviti povsod, kjer kličeš funkcijo `url`, torej v pythonu in v htmljih.

Ostala koda mi izgleda ok. Poskusi to čimprej popraviti in javi, da pregledam projekt še vsebinsko. Če binder še vedno ne bo uspešno zagnalo, prav tako sporoči, da pogledam kje so še težave.

**Comment by valentinamacek** [comment]
Živjo, 

hvala za pomoč, sem popravila in zdj binder deluje :).

**Comment by majbc1999** [comment]
Živjo,
za vsebinski test aplikacije bi rabil kakšno uporabniško ime oz. geslo, da se lahko vpišem v aplikacijo.

**Comment by valentinamacek** [comment]
Evo lahko kot admin: up: vale in geslo: izzy

**Comment by majbc1999** [comment]
Torej, našel sem dve manjši težavici, ki bi jih izpostavil:

1. Ko želim dodati nov ICŽP in specificiram napačno (neobstoječo) šifro skupine, aplikacija crasha:
![image](https://github.com/user-attachments/assets/181cdc40-27fb-4c77-8960-5ddad667d03d)
To ni ok. Treba je pogledati ta robni primer in uporabniku aplikacije nekako sporočiti, da je izbral napačno šifro skupine. Druga možna rešitev je, da si uporabnik izbere šifro izmed vseh možnih šifer (npr. drop down list).

2.  Opcijsko (za boljšo oceno): prijavni zaslon je neoblikovan. Poskusi dodati isto oblikovanje z bootstrapom, kot si to storila drugod.

Ostalo dela, tako kot mora. Ko končaš, sporoči, da preverim, če je kul in potem odobrim projekt :D

**Comment by valentinamacek** [comment]
Evo,  sem popravila te dve stvari :).

**Comment by majbc1999** [comment]
Ojla, izgleda super in dela. Lahko se z @jaanos zmeniš za ustni zagovor. Srečno!

**Comment by valentinamacek** [comment]
Hvala za vse :D
